"""add manual_topics and manual_keywords to articles

Revision ID: 142c7808aebe
Revises: 365a89923dca
Create Date: 2026-05-10 04:22:09.451903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '142c7808aebe'
down_revision: Union[str, Sequence[str], None] = '365a89923dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('articles', sa.Column('manual_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('articles', sa.Column('manual_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE articles SET manual_topics = '[]', manual_keywords = '[]'")
    op.alter_column('articles', 'manual_topics', nullable=False)
    op.alter_column('articles', 'manual_keywords', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'manual_keywords')
    op.drop_column('articles', 'manual_topics')
    # ### end Alembic commands ###
