"""add_source_flashcard_ids_to_quiz_attempts

Revision ID: 365a89923dca
Revises: 7ee89cbfe563
Create Date: 2026-05-03 10:55:58.341986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '365a89923dca'
down_revision: Union[str, Sequence[str], None] = '7ee89cbfe563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('source_flashcard_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'source_flashcard_ids')
    # ### end Alembic commands ###
